[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'chriskempson/vim-tomorrow-theme'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = "tpope/vim-fugitive"
hook_add = 'source ~/.config/nvim/userautoload/plugins/plugins-vim-fugitive.vim'

