[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
  " denite キー
  noremap [denite] <Nop>
  nmap <C-d> [denite]

  " v で vsplit
  call denite#custom#map('normal', "v", '<denite:do_action:vsplit>')

  " [denite]<C-g> でgrep
  nnoremap <silent> [denite]<C-g> :<C-u>Denite grep
    \ -no-empty -mode=normal<CR>

  " [denite]<C-k> で単語単位での grep
  " (カーソル下の単語をレジスタzへ格納しペースト)
  nnoremap <silent> [denite]<C-k>
    \ "zyiw:<C-u>Denite grep:::\\b<C-r>z\\b
    \ -no-empty -mode=normal<CR>

  " [denite]<C-n> で検索結果を開き直す
  nnoremap <silent> [denite]<C-r> :<C-u>Denite -resume
    \ -no-empty -mode=normal<CR>

  " [denite]<C-n> で次の検索結果へ
  nnoremap <silent> [denite]<C-n> :<C-u>Denite -resume
    \ -cursor-pos=+1 -immediately<CR>

  " [denite]<C-p> で前の検索結果へ
  nnoremap <silent> [denite]<C-p> :<C-u>Denite -resume
    \ -cursor-pos=-1 -immediately<CR>

  " [denite]<C-f> でファイル一覧
  nnoremap <silent> [denite]<C-f> :<C-u>Denite file/rec
    \ -no-empty<CR>

  " [denite]<C-d> で dotfiles 編集
  nnoremap <silent> [denite]<C-d> :<C-u>call denite#start(
    \ [{'name': 'file_rec', 'args': ['~/dotfiles']}])<CR>

  " ripgrep 使用
  if executable('rg')
    call denite#custom#var('file/rec', 'command',
      \ ['rg', '--files', '--glob', '!.git'])
    call denite#custom#var('grep', 'command', ['rg', '--vimgrep', '--no-heading'])
    call denite#custom#var('grep', 'default_opts', [])
    call denite#custom#var('grep', 'recursive_opts', [])
    call denite#custom#var('grep', 'pattern_opt', ['--regexp'])
    call denite#custom#var('grep', 'separator', ['--'])
    call denite#custom#var('grep', 'final_opts', [])
  endif
'''

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'chriskempson/vim-tomorrow-theme'

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
  nnoremap [fugitive]  <Nop>
  nmap <C-g> [fugitive]
  nnoremap <silent> [fugitive]<C-s> :Gstatus<CR><C-w>T
  nnoremap <silent> [fugitive]<C-d> :Gvdiff<CR>
  nnoremap <silent> [fugitive]<C-a> :Gwrite<CR>
  nnoremap <silent> [fugitive]<C-b> :Gblame<CR>
  nnoremap <silent> [fugitive]<C-m> :Gmerge<CR>
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  let g:lightline = {
    \ 'colorscheme': 'Tomorrow',
    \ 'active': {
    \   'left': [ [ 'mode', 'paste' ],
    \             [ 'gitbranch', 'readonly', 'filename', 'modified' ] ]
    \ },
    \ 'component_function': {
    \   'gitbranch': 'fugitive#head'
    \ },
  \ }

  " show statusbar
  set laststatus=2

  " hide --INSERT--
  set noshowmode
'''

[[plugins]]
repo = 'kassio/neoterm'
hook_add = '''
  " :Tnew の場合に挿入モードで開始
  let g:neoterm_autoinsert = 1

  " :T {cmd} 実行時に画面スクロールする
  let g:neoterm_autoscroll = 1

  "let g:neoterm_default_mod = 'vertical'   " 縦分割
  let g:neoterm_default_mod = 'belowright'  " 横分割

  " :Tnew 実行
  nnoremap <silent> <C-e><C-t> :Tnew<CR>

  " :Tnew 実行(縦分割)
  nnoremap <silent> <C-e><C-v> :vertical Tnew<CR>

  " 現在の行を実行
  nnoremap <silent> <C-e><C-e> :TREPLSendLine<CR>

  " ビジュアルモードで選択中の行を実行
  vnoremap <silent> <C-e><C-e> V:TREPLSendSelection<CR>

  " ファイルそのものを実行
  nnoremap <silent> <C-e><C-f> :TREPLSendFile<CR>

  " <Esc> で terminal-mode を抜ける
  tnoremap <Esc> <C-\><C-n>

  " <C-w> で ウィンドウ移動
  tnoremap <C-w><C-w> <C-\><C-n><C-w><C-w>
  tnoremap <C-w><C-j> <C-\><C-n><C-w><C-j>
  tnoremap <C-w><C-k> <C-\><C-n><C-w><C-k>
  tnoremap <C-w><C-h> <C-\><C-n><C-w><C-h>
  tnoremap <C-w><C-l> <C-\><C-n><C-w><C-l>
'''

