[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'chriskempson/vim-tomorrow-theme'

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
  nnoremap [fugitive]  <Nop>
  nmap <C-g> [fugitive]
  nnoremap <silent> [fugitive]<C-s> :Gstatus<CR><C-w>T
  nnoremap <silent> [fugitive]<C-d> :Gvdiff<CR>
  nnoremap <silent> [fugitive]<C-a> :Gwrite<CR>
  nnoremap <silent> [fugitive]<C-b> :Gblame<CR>
  nnoremap <silent> [fugitive]<C-m> :Gmerge<CR>
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  let g:lightline = {
    \ 'colorscheme': 'Tomorrow',
    \ 'active': {
    \   'left': [ [ 'mode', 'paste' ],
    \             [ 'gitbranch', 'readonly', 'filename', 'modified' ] ]
    \ },
    \ 'component_function': {
    \   'gitbranch': 'fugitive#head'
    \ },
  \ }

  " show statusbar
  set laststatus=2

  " hide --INSERT--
  set noshowmode
'''

[[plugins]]
repo = 'kassio/neoterm'
hook_add = '''
  " :Tnew の場合に挿入モードで開始
  let g:neoterm_autoinsert = 1

  " :T {cmd} 実行時に画面スクロールする
  let g:neoterm_autoscroll = 1

  "let g:neoterm_default_mod = 'vertical'   " 縦分割
  let g:neoterm_default_mod = 'belowright'  " 横分割

  " :Tnew 実行
  nnoremap <silent> <C-e><C-t> :Tnew<CR>

  " :Tnew 実行(縦分割)
  nnoremap <silent> <C-e><C-v> :vertical Tnew<CR>

  " 現在の行を実行
  nnoremap <silent> <C-e><C-e> :TREPLSendLine<CR>

  " ビジュアルモードで選択中の行を実行
  vnoremap <silent> <C-e><C-e> V:TREPLSendSelection<CR>

  " ファイルそのものを実行
  nnoremap <silent> <C-e><C-f> :TREPLSendFile<CR>

  " <Esc> で terminal-mode を抜ける
  tnoremap <Esc> <C-\><C-n>

  " <C-w> で ウィンドウ移動
  tnoremap <C-w><C-w> <C-\><C-n><C-w><C-w>
  tnoremap <C-w><C-j> <C-\><C-n><C-w><C-j>
  tnoremap <C-w><C-k> <C-\><C-n><C-w><C-k>
  tnoremap <C-w><C-h> <C-\><C-n><C-w><C-h>
  tnoremap <C-w><C-l> <C-\><C-n><C-w><C-l>
'''

