# tomlファイル syntax
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

# ruby 編集時 end を自動で補完
[[plugins]]
repo = 'tpope/vim-endwise'
on_i = 1
on_ft = ['ruby']

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#auto_complete_delay = 0
  inoremap <expr><tab> pumvisible() ? "\<C-n>" : "\<tab>"
'''
on_i = 1

